name: xbt_client
description: "A new Flutter project that can sign XXT signature"
publish_to: 'none'
version: 1.1.0+2


environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  extended_image: ^9.1.0
  flutter_gesture_password: ^0.0.2
  rounded_expansion_tile: ^0.0.13
  badges: ^3.1.2
  dio: ^5.8.0+1
  encrypt: ^5.0.1
  flutter_smart_dialog: ^4.9.8+7
  adaptive_dialog: ^2.4.0
  coordtransform_dart: ^1.0.4
  restart_app: ^1.3.2
  shared_preferences: ^2.5.2
  mobile_scanner: ^6.0.7
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/keys/
    - assets/images/
